name: Deploy Website

on:
  push:
    branches:
      - main  # Trigger deployment on code push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      run: echo "dckr_pat_-3CAZ73gLl3hiewT3Skoo3fGuw8" | docker login -u "kartikverma880" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t kartikverma880/portfolio-website:latest .
        docker push kartikverma880/portfolio-website:latest

    - name: Deploy Docker Compose
      run: |
        docker-compose up -d
